server:
  port: 3344

spring:
  application:
    name:  cloud-config-center-3344
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cllnv/spingcloud-config.git   #GitHub上面的git仓库名字
          label: mddfdfaster